[package]
name = "noaa-spc-rss-watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.4"
rss = "2.0.7"
scraper = "0.19.0"
tokio = { version = "1.37.0", features = ["full"] }
